SELECT
    p.PF_CODE AS "都道府県コード",
    p.PF_NAME AS "都道府県名",
    p2015.TOTAL_AMT AS "総人口2015年",
    p2020.TOTAL_AMT AS "総人口2020年",
    ROUND(CAST(p2020.TOTAL_AMT AS real)/CAST(p2015.TOTAL_AMT AS real)*100) AS "人口増加率"
FROM
    PREFECTURE AS p
    JOIN POPU_TRANSITION AS pt ON p.PF_CODE = pt.PF_CODE
    JOIN (SELECT TOTAL_AMT, PF_CODE FROM POPU_TRANSITION WHERE SURVEY_YEAR = "2015") AS p2015 ON p2015.PF_CODE = p.PF_CODE
    JOIN (SELECT TOTAL_AMT, PF_CODE FROM POPU_TRANSITION WHERE SURVEY_YEAR = "2020") AS p2020 ON p2020.PF_CODE = p.PF_CODE
WHERE
    p2020.TOTAL_AMT - p2015.TOTAL_AMT > 0
GROUP BY
    p.PF_CODE
ORDER BY
    "人口増加率" DESC,
    "都道府県コード" ASC;